# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import injure_pb2 as injure__pb2


class InjureStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Methods = channel.unary_unary(
        '/injure.Injure/Methods',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=injure__pb2.Response.FromString,
        )
    self.RecoverAll = channel.unary_unary(
        '/injure.Injure/RecoverAll',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.RecoverMethod = channel.unary_unary(
        '/injure.Injure/RecoverMethod',
        request_serializer=injure__pb2.Request.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.SetFault = channel.unary_unary(
        '/injure.Injure/SetFault',
        request_serializer=injure__pb2.Request.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.SetFaultAll = channel.unary_unary(
        '/injure.Injure/SetFaultAll',
        request_serializer=injure__pb2.Request.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class InjureServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Methods(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RecoverAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RecoverMethod(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetFault(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetFaultAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InjureServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Methods': grpc.unary_unary_rpc_method_handler(
          servicer.Methods,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=injure__pb2.Response.SerializeToString,
      ),
      'RecoverAll': grpc.unary_unary_rpc_method_handler(
          servicer.RecoverAll,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'RecoverMethod': grpc.unary_unary_rpc_method_handler(
          servicer.RecoverMethod,
          request_deserializer=injure__pb2.Request.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'SetFault': grpc.unary_unary_rpc_method_handler(
          servicer.SetFault,
          request_deserializer=injure__pb2.Request.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'SetFaultAll': grpc.unary_unary_rpc_method_handler(
          servicer.SetFaultAll,
          request_deserializer=injure__pb2.Request.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'injure.Injure', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
